language: objective-c
osx_image: xcode11.6
cache: cocoapods

env:
  global:
  - LANG=en_US.UTF-8

  - WORKSPACE="OTTextChatAccelerator.xcworkspace"
  - IOS_SCHEME="OTTextChatAccelerator"
  - IOS_SDK=iphonesimulator13.6

  matrix:
  - DESTINATION="OS=12.4,name=iPhone 6s"     SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="YES" RUN_UI_TESTS="NO"
  - DESTINATION="OS=13.6,name=iPhone 11 Pro"   SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="YES" RUN_UI_TESTS="NO"

before_install:
  - gem install cocoapods --pre
  - pod update

script:
- set -o pipefail

- if [ $POD_LINT == "YES" ]; then
    pod lib lint --use-libraries --allow-warnings --verbose;
  fi

- if [ $RUN_TESTS == "YES" ]; then
    travis_retry xcodebuild clean build test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  else
    travis_retry xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi

notifications:
  slack:
    rooms:
      secure: EP4tKC/05pS1+DztuIKZF8EoCNuj24JnrJgg6SgV3oTJqayYLm8cuY18fNGWN0jLOQThoXuasiABWP2Gx/wJv/c2iDWZIZtr+MH6emqPFE7EzqsQktRrvwjICwBGr50C4bG2SZ8INgSXVxC9QvcgbM3SAQtSgqxsk8CHY6ar/q1lnahFBjuwr+Fzv3HSDs0rFMo0k7EaOQoqc2K/+TQvwDj39ZcbQDy0948YQU6wdbIsJoT74n6FwIvSnv6b7FI730LAoSEyC6/hxjWvHsq5E6apKI332HDjpXqYYvBpm023f9DDVVpYgX1L0KIsNYR3lIWXrA2fYCkmvfA7KEN7Oj0rniI9WINEiJqGOLDY5ADCoXbeuMZix6jle/lAAN9r7UxqAe4i+itJr1GkuYAQ7AnLuBPqGycc08uAOuhUvGUJA+gviYGjquxtbI3x9tOfzv3U/HIrntOiW1svcUcx2eeqj3Y7ft0GAChHVXlh3vunT5VoakqRVfsxwoUUIRmmKAi4yljUiiol15lWpbJhQJpS4XiyIYovsywmBQ/EE2xBAkoo6TmvPHDpT+nHH8Pb4LjVpFJlzfIQmiPtuSJCfufeVM0hHjdnkVh7dxQ6S8yoyVvoKZ64yd2sty8Jcx816ymqLCSlfXuqAJuBHVaW5P/rj+tU6PK5Odri8anWNDk=
